# -*- coding: utf-8 -*-
"""Aula06.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mdHJOK62_Kb3TLBE_z6mxTcn5wulFNdY

Execicios 01

Escreva um programa que calcule a porcentagem de comissão de vendedores com as seguintes condições

Venda Total
de R$ 0.00 a R$ 30000.00 - 0%
de R$ 30000.01 a R$ 50000.00 - 1.5%
de R$ 50000.01 a R$ 100000.00 - 2.5%
Acima de R$ 100000.00 - 3.5%
"""



"""Execicios 02

Escreva um programa que receba 4 notas e calcule a média.
Mostre a seguinte mensagem conforme a media final.

Media Final
de 0 a 5 - Reprovado
de 5 a 6.5 - Recuperação
de 6.5 a 9 - Aprovado
Acima de 9 - Aprovado com louvor
"""



"""Execicios 03

Escreva um programa que contenha um menu com 4 opções:
A) soma
B) média
C) divisão
D) Sair

As opções podem ser escolhidas com as letras maiusculas ou minusculas.

Para a opção soma, deve solicitar 2 números, fazer a soma e mostrar o resultado.

Para a opção média, deve solicitar 4 números, fazer a média e mostrar os resultados.

Para a opção divisão, deve solicitar 2 números, dividir o primeiro pelo segundo e montrar o resultado. Caso o segundo for igual a 0, então deve mostrar o a mensagem "Erro! Não pode dividir por ZERO!"

Para a opção sair, deve aparecer a mensagem: "Muito Obrigado e Volte sempre!"
"""



"""Execicios 04
Exercicio retirado do site <https://wiki.python.org.br/EstruturaDeDecisao>

Faça um Programa que peça os 3 lados de um triângulo. O programa deverá informar se os valores podem ser um triângulo. Indique, caso os lados formem um triângulo, se o mesmo é: equilátero, isósceles ou escaleno.
Dicas:

Três lados formam um triângulo quando a soma de quaisquer dois lados for maior que o terceiro;

Triângulo Equilátero: três lados iguais;

Triângulo Isósceles: quaisquer dois lados iguais;

Triângulo Escaleno: três lados diferentes;
"""



